version: '3'

services:
  web:
    build: .
    env_file: config/blog.env
    ports:
      - '8080:8080'
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./config/schema.sql:/docker-entrypoint-initdb.d/schema.sql
